services:
  mariadb:
    image: mariadb:latest
    user: "977:988"
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: luckperms
      MYSQL_USER: luckperms
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /mnt/server-storage/minecraft/db:/var/lib/mysql
    networks:
      - minecraft
  redis:
    image: redis:latest
    user: "977:988"
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /mnt/server-storage/minecraft/redis:/data
    networks:
      - minecraft

  ingress:
    image: ghcr.io/minekube/gate:latest
    restart: unless-stopped
    ports:
      - target: 25565
        published: 25565
        protocol: tcp
        mode: host
      - target: 25565
        published: 25565
        protocol: udp
        mode: host
    volumes:
      - ./ingress.yml:/config/config.yml:ro
    networks:
      - minecraft

networks:
  minecraft:
    external: true
    name: minecraft