services:
  lobby:
    image: itzg/minecraft-server:latest
    env_file:
      - ./.env
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.8"
      MEMORY: "3G"
      DIFFICULTY: peaceful
      USE_AIKAR_FLAGS: "true"
      ONLINE_MODE: "false"
      REMOVE_OLD_MODS: "true"
      GENERIC_PACKS: common,lobby
      GENERIC_PACKS_PREFIX: http://archives.internal/server_setup/
      GENERIC_PACKS_SUFFIX: .zip
      # Configs
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      CFG_FORWARDING_SECRET: ${FORWARDING_SECRET}
      CFG_LUCKPERMS_SERVER: lobby
    labels:
      - "velocity.enable=true"
      - "velocity.port=25565"
      - "velocity.group=lobby"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    networks:
      - minecraft

networks:
  minecraft:
    external: true
    name: minecraft